### ISSUE TITLE
Binding for clockboard function

### ISSUE THREAD

**Issue by pkopparla** [zonebuilders/zonebuilder-py#3]
Would be good to have a binding for the clockboard function. But it's unclear how best to pass the resulting geojson around.

**Comment by dabreegster** [comment]
Great question. The approach we took for the WebAssembly bindings is rather brute-force -- just return the raw JSON string, then re-parse it in Javascript. We could do the same for Python, and people can then use https://pypi.org/project/geojson/ or whatever else they like. I'm not familiar with pyO3, but I'd guess it's lots of trouble to find a Python representation for GeoJSON and somehow make Rust structs mapping over to that

**Comment by pkopparla** [comment]
Yes exactly, I struggled with that for a couple of hours, and then found a very convenient rust crate: https://crates.io/crates/pythonize
This is what is being used now to pass the geojson back as a python dictionary. Is this alright? Edit: addressed in the PR.

**Comment by dabreegster** [comment]
Well, what's the experience of using the result in Python look like? Does the Pythonized mapping of https://docs.rs/geojson/0.22.2/geojson/struct.Feature.html look reasonable? It might be easier to return the JSON string and just handle it in Python normally.
