### ISSUE TITLE
Documentation and preparing for release

### ISSUE THREAD

**Issue by pkopparla** [zonebuilders/zonebuilder-py#5]
Hello,

Since the bindings are done, I thought we'd want to have this package easily available for download from `pip` which means uploading to pypi.org. Might be a good idea to have a few issues sorted out before that:
1. Documentation: At the moment it's just about dev stuff, is it a good idea to copy over images and descriptions from `zonebuilder-rust/README.md`?
2. Adding a test for the `clockboard` function? Any suggestions for a test case or just use the output from `zonebuilder-rust/examples/clockboard-example.rs` written to a json file and compared against a local run?
3. License? Author order convention?
4. Any other points?

**Comment by dabreegster** [comment]
Thanks for doing all the work to hook up to the Python ecosystem!

> Documentation

Sure, the Python docs should probably be pretty self-contained, so copying makes sense

> Adding a test for the clockboard function?

We have some ideas for more unit tests to write on the Rust side, just never got around to it: https://github.com/zonebuilders/zonebuilder-rust/issues/11
There's a bare minimum test now: https://github.com/zonebuilders/zonebuilder-rust/blob/b3588689eb11f966ee6dc56e2f4c5416b819c533/src/lib.rs#L260
I don't think duplicating all the "API contract" tests from Rust makes sense. The Python tests should just demonstrate that the bindings work. So yeah, you could just call `clockboard` and compare the results to a hard-coded, manually verified output from the Rust tool. Or parse the result with `json.loads` and assert the number of zones or something like that.

> License

I'd vote for consistency: https://github.com/zonebuilders/zonebuilder-rust/blob/main/LICENSE

**Comment by pkopparla** [comment]
The package is out on pypi here: https://pypi.org/project/zonebuilder/1.0.1/
You can give it a try by typing `pip install zonebuilder` from python environments.
If you guys create accounts on pypi and tell me your usernames, I can give you ownership of the distribution.

**Comment by Robinlovelace** [comment]
This is so cool! Amazing work @pkopparla !

**Comment by pkopparla** [comment]
I learned a lot from doing this, and it was great collaborating with you :)
